-- Schema-only baseline observed through Supabase SQL Editor, 2026-09-08.
-- No remote rows or credentials. Used only by disposable PGlite tests.
create table public.artists (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), name text, slug text,
  spotify_id text, image_url text, description text,
  is_verified boolean default false, updated_at timestamptz default now()
);
create table public.albums (
  id bigint generated by default as identity primary key,
  spotify_id text unique, artist_id bigint references public.artists(id) on delete cascade,
  title text not null, slug text not null unique, cover_url text, release_date date,
  album_type text not null check (album_type in ('album','ep')), description text,
  is_verified boolean default false, created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create table public.tracks (
  id bigint generated by default as identity primary key,
  album_id bigint references public.albums(id) on delete cascade,
  spotify_id text, title text not null, track_number integer not null,
  duration_ms integer, created_at timestamptz default now()
);
create table public.track_artists (
  id bigint generated by default as identity primary key,
  track_id bigint references public.tracks(id) on delete cascade,
  artist_id bigint references public.artists(id) on delete cascade,
  role text not null check (role in ('main','feature')),
  unique (track_id,artist_id,role)
);
alter table public.artists enable row level security;
alter table public.albums enable row level security;
alter table public.tracks enable row level security;
alter table public.track_artists enable row level security;
-- Existing grants are broad, but RLS has no policies and blocks public rows.
grant all on public.artists, public.albums, public.tracks, public.track_artists
  to anon, authenticated, service_role;
