import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { safeNextPath, validateEmail, validatePassword, validateUsername } from "../src/lib/auth-validation.ts";
import { siteUrl } from "../src/lib/site-url.ts";
import { countryFilter } from "../src/lib/countries.ts";

const migration = await readFile(new URL("../supabase/migrations/202609080002_auth_community.sql", import.meta.url), "utf8");
const commentLikesMigration = await readFile(new URL("../supabase/migrations/202609080003_comment_likes.sql", import.meta.url), "utf8");
const artistRatingsMigration = await readFile(new URL("../supabase/migrations/202609080004_artist_ratings.sql", import.meta.url), "utf8");
const publicProfilesMigration = await readFile(new URL("../supabase/migrations/202609090005_public_profiles.sql", import.meta.url), "utf8");
const commentThreadsMigration = await readFile(new URL("../supabase/migrations/202609090006_comment_threads.sql", import.meta.url), "utf8");
const catalogSubmissionsMigration = await readFile(new URL("../supabase/migrations/202609090007_catalog_submissions.sql", import.meta.url), "utf8");
const profileSubmissionStatsMigration = await readFile(new URL("../supabase/migrations/202609090008_profile_submission_stats.sql", import.meta.url), "utf8");
const artistSubmissionStatsMigration = await readFile(new URL("../supabase/migrations/202609090009_artist_submission_album_stats.sql", import.meta.url), "utf8");
const persistentImportQueueMigration = await readFile(new URL("../supabase/migrations/202609090010_persistent_import_queue.sql", import.meta.url), "utf8");
const incompleteCatalogSubmissionMigration = await readFile(new URL("../supabase/migrations/202609090011_allow_incomplete_catalog_submissions.sql", import.meta.url), "utf8");
const moderationNotificationsMigration = await readFile(new URL("../supabase/migrations/202609100012_moderation_notifications.sql", import.meta.url), "utf8");
const importLeasesMigration = await readFile(new URL("../supabase/migrations/202609100013_import_leases_and_retries.sql", import.meta.url), "utf8");
const recentlyRatedAlbumsMigration = await readFile(new URL("../supabase/migrations/202609100014_recently_rated_albums.sql", import.meta.url), "utf8");
const closedAlphaToolsMigration = await readFile(new URL("../supabase/migrations/202609100015_closed_alpha_tools.sql", import.meta.url), "utf8");
const concertsMigration = await readFile(new URL("../supabase/migrations/202609110016_concerts_and_ticket_offers.sql", import.meta.url), "utf8");
const adminStatsMigration = await readFile(new URL("../supabase/migrations/202609110017_admin_dashboard_stats.sql", import.meta.url), "utf8");
const artistCountriesMigration = await readFile(new URL("../supabase/migrations/202609110018_artist_countries.sql", import.meta.url), "utf8");
const artistVisibilityMigration = await readFile(new URL("../supabase/migrations/202609110019_artist_catalog_visibility.sql", import.meta.url), "utf8");
const albumGenresMigration = await readFile(new URL("../supabase/migrations/202609110020_album_genres.sql", import.meta.url), "utf8");
const activeUsersMigration = await readFile(new URL("../supabase/migrations/202609110021_active_users_leaderboard.sql", import.meta.url), "utf8");
const artistEnrichmentMigration = await readFile(new URL("../supabase/migrations/202609130022_artist_enrichment.sql", import.meta.url), "utf8");
const artistBiographiesMigration = await readFile(new URL("../supabase/migrations/202609130025_artist_biographies.sql", import.meta.url), "utf8");
const removeArtistBiographiesMigration = await readFile(new URL("../supabase/migrations/202609130026_remove_artist_biographies.sql", import.meta.url), "utf8");
const draftSchema = `
  create role anon;
  create role authenticated;
  create role service_role bypassrls;
  create schema auth;
  create schema storage;
  create table auth.users (
    id uuid primary key,
    raw_user_meta_data jsonb not null default '{}'::jsonb
  );
  create function auth.uid() returns uuid language sql stable
    as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  create function storage.foldername(name text) returns text[] language sql immutable
    as $$ select string_to_array(name, '/') $$;
  create table storage.buckets (
    id text primary key, name text not null, public boolean not null default false,
    file_size_limit bigint, allowed_mime_types text[]
  );
  create table storage.objects (
    id bigint generated by default as identity primary key,
    bucket_id text not null references storage.buckets(id), name text not null
  );
  alter table storage.objects enable row level security;
  grant usage on schema public, auth, storage to anon, authenticated, service_role;
  grant execute on function auth.uid() to anon, authenticated;
  grant execute on function storage.foldername(text) to anon, authenticated;
  grant select on storage.objects to anon, authenticated;
  grant insert, update, delete on storage.objects to authenticated;
  create table public.artists (id bigint generated by default as identity primary key, name text, slug text, image_url text);
  create table public.albums (id bigint generated by default as identity primary key, title text, slug text);
  create table public.album_artists (album_id bigint references public.albums(id), artist_id bigint references public.artists(id), position integer, primary key(album_id,artist_id));
  grant select on public.artists, public.albums, public.album_artists to anon, authenticated;
  create table public.users (id bigint primary key, username text not null, email text unique, avatar_url text, role text default 'user', created_at timestamptz default now(), updated_at timestamptz default now());
  create table public.ratings (id bigint primary key, user_id bigint references public.users(id), album_id bigint references public.albums(id), rating numeric not null, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,album_id));
  create table public.comments (id bigint primary key, user_id bigint references public.users(id), album_id bigint references public.albums(id), content text not null, created_at timestamptz default now(), updated_at timestamptz default now());
  create table public.listened (id bigint primary key, user_id bigint references public.users(id), album_id bigint references public.albums(id), created_at timestamptz default now(), unique(user_id,album_id));
  create table public.want_to_listen (id bigint primary key, user_id bigint references public.users(id), album_id bigint references public.albums(id), created_at timestamptz default now(), unique(user_id,album_id));
  alter table public.users enable row level security;
  alter table public.ratings enable row level security;
  alter table public.comments enable row level security;
  alter table public.listened enable row level security;
  alter table public.want_to_listen enable row level security;
`;

test("auth input validation rejects unsafe redirects and invalid credentials", () => {
  assert.equal(safeNextPath("/album/test"), "/album/test");
  assert.equal(safeNextPath("//evil.example", "/"), "/");
  assert.equal(safeNextPath("https://evil.example", "/profil"), "/profil");
  assert.equal(validateEmail(" USER@example.com "), "user@example.com");
  assert.equal(validateEmail("wrong"), null);
  assert.equal(validateUsername("Tape_User"), "Tape_User");
  assert.equal(validateUsername("nie poprawne"), null);
  assert.equal(validatePassword("album123"), "album123");
  assert.equal(validatePassword("short1"), null);
});

test("password recovery keeps the current local host and rejects foreign origins", () => {
  const configured = process.env.NEXT_PUBLIC_SITE_URL;
  delete process.env.NEXT_PUBLIC_SITE_URL;

  try {
    assert.equal(siteUrl("http://127.0.0.1:3000/reset-hasla"), "http://127.0.0.1:3000");
    assert.equal(siteUrl("http://localhost:3000/reset-hasla"), "http://localhost:3000");
    assert.equal(siteUrl("https://evil.example/reset-hasla"), "http://localhost:3000");
  } finally {
    if (configured === undefined) delete process.env.NEXT_PUBLIC_SITE_URL;
    else process.env.NEXT_PUBLIC_SITE_URL = configured;
  }
});

test("artist origin defaults to Poland and keeps explicit alternatives", () => {
  assert.equal(countryFilter(undefined), "PL");
  assert.equal(countryFilter("PL"), "PL");
  assert.equal(countryFilter("INT"), "INT");
  assert.equal(countryFilter("all"), "all");
});

test("community migration connects Auth, RLS, ratings, comments and lists", async () => {
  const db = new PGlite();
  const alice = "11111111-1111-4111-8111-111111111111";
  const bob = "22222222-2222-4222-8222-222222222222";
  try {
    await db.exec(draftSchema);
    await db.exec(migration);
    await db.exec(commentLikesMigration);
    await db.exec(artistRatingsMigration);
    await db.exec(publicProfilesMigration);
    await db.exec(commentThreadsMigration);
    await db.exec("alter table public.artists add column spotify_id text, add column description text, add column updated_at timestamptz default now(); alter table public.albums add column spotify_id text;");
    await db.exec(catalogSubmissionsMigration);
    await db.exec(profileSubmissionStatsMigration);
    const columns = await db.query<{ table_name: string; column_name: string; data_type: string }>(`
      select table_name,column_name,data_type from information_schema.columns
      where table_schema='public' and ((table_name='users' and column_name='id') or (table_name='ratings' and column_name='user_id'))
      order by table_name,column_name`);
    assert.deepEqual(columns.rows, [
      { table_name: "ratings", column_name: "user_id", data_type: "uuid" },
      { table_name: "users", column_name: "id", data_type: "uuid" },
    ]);

    await db.query("insert into public.artists(name,slug) values ('Artysta','artysta')");
    await db.query("insert into public.albums(title,slug) values ('Album','album')");
    await db.query("insert into public.album_artists(album_id,artist_id,position) values (1,1,0)");
    await db.query("insert into auth.users(id,raw_user_meta_data) values ($1,$2::jsonb),($3,$4::jsonb)", [alice, JSON.stringify({ username: "Alice" }), bob, JSON.stringify({ username: "Bob" })]);
    assert.deepEqual((await db.query("select username,role from public.users order by username")).rows, [
      { username: "Alice", role: "user" }, { username: "Bob", role: "user" },
    ]);

    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.exec("set role authenticated");
    await db.query("select public.submit_spotify_catalog_item('album','1234567890123456789012','Nowy album','https://i.scdn.co/image/test')");
    await db.query("select public.submit_spotify_catalog_item('album','1234567890123456789012','Nowy album','https://i.scdn.co/image/test')");
    await db.query("select public.submit_spotify_catalog_item('artist','AAAAAAAAAAAAAAAAAAAAAA','Nowy artysta','https://i.scdn.co/image/test')");
    assert.equal((await db.query("select * from public.catalog_submissions")).rows.length, 2);
    assert.equal((await db.query("select * from public.catalog_submission_supporters")).rows.length, 2);
    await db.exec("reset role");
    await db.query("update public.artists set spotify_id='AAAAAAAAAAAAAAAAAAAAAA' where id=1");
    await db.query("update public.albums set spotify_id='1234567890123456789012' where id=1");
    await db.query("insert into public.albums(title,slug,spotify_id) values ('Drugi album','drugi-album','CCCCCCCCCCCCCCCCCCCCCC')");
    await db.query("insert into public.album_artists(album_id,artist_id,position) values (2,1,0)");
    await db.query("update public.catalog_submissions set status='imported'");
    await db.exec(artistSubmissionStatsMigration);
    await db.exec(persistentImportQueueMigration);
    await db.exec(incompleteCatalogSubmissionMigration);
    await db.exec(moderationNotificationsMigration);
    await db.exec(importLeasesMigration);
    await db.exec(recentlyRatedAlbumsMigration);
    await db.exec(closedAlphaToolsMigration);
    await db.exec(concertsMigration);
    await db.exec(adminStatsMigration);
    await db.exec(artistCountriesMigration);
    await db.exec(artistVisibilityMigration);
    await db.exec(albumGenresMigration);
    await db.exec(activeUsersMigration);
    await db.exec(artistEnrichmentMigration);
    await db.exec(artistBiographiesMigration);
    await db.exec(removeArtistBiographiesMigration);
    assert.deepEqual((await db.query("select distinct country_code from public.artists")).rows, [{ country_code: "PL" }]);
    assert.deepEqual((await db.query("select distinct genre from public.albums")).rows, [{ genre: "rap" }]);

    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.exec("set role authenticated");
    const biography = "Polski artysta związany ze sceną hip-hopową. Rozwija własną dyskografię, współpracuje z innymi wykonawcami i regularnie publikuje nowe nagrania.";
    const biographySubmission = await db.query<{ submit_artist_biography: bigint }>(
      "select public.submit_artist_biography(1,$1)", [biography],
    );
    await db.exec("reset role");
    await db.query("update public.users set role='admin' where id=$1", [bob]);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [bob]);
    await db.exec("set role authenticated");
    await db.query("select public.moderate_artist_biography($1,'approve',null)", [biographySubmission.rows[0].submit_artist_biography]);
    await db.exec("reset role");
    assert.deepEqual((await db.query("select description,biography_author_id::text from public.artists where id=1")).rows, [
      { description: biography, biography_author_id: alice },
    ]);
    await db.exec("set role anon");
    assert.equal((await db.query<{ count: string }>("select public.accepted_biography_count($1)::text as count", [alice])).rows[0].count, "1");
    await db.exec("reset role");
    await db.exec("set role authenticated");
    await db.query("select public.remove_artist_biography(1,'Nieaktualna treść')");
    await db.exec("reset role");
    assert.deepEqual((await db.query("select description,biography_author_id from public.artists where id=1")).rows, [
      { description: null, biography_author_id: null },
    ]);
    assert.deepEqual((await db.query("select status,removal_reason from public.artist_biography_submissions where id=$1", [biographySubmission.rows[0].submit_artist_biography])).rows, [
      { status: "removed", removal_reason: "Nieaktualna treść" },
    ]);
    await db.exec("set role anon");
    assert.equal((await db.query<{ count: string }>("select public.accepted_biography_count($1)::text as count", [alice])).rows[0].count, "0");
    await db.exec("reset role");
    await db.query("update public.users set role='user' where id=$1", [bob]);
    const leaderboard = await db.query<{ username: string; activity_score: bigint }>(
      "select username, activity_score from public.community_user_leaderboard(30, 5)",
    );
    assert.equal(leaderboard.rows[0]?.username, "Alice");
    assert.ok(Number(leaderboard.rows[0]?.activity_score ?? 0) > 0);
    assert.deepEqual((await db.query("select catalog_visible from public.artists")).rows, [{ catalog_visible: true }]);
    const worker = "33333333-3333-4333-8333-333333333333";
    await db.query(`insert into public.catalog_import_jobs
      (submission_id,spotify_type,spotify_id,title,status,locked_until)
      values (1,'album','1234567890123456789012','Przerwany album','running',now()-interval '1 minute')`);
    await db.query(`insert into public.catalog_import_items
      (job_id,spotify_album_id,title,album_type,status)
      values (1,'1234567890123456789012','Przerwany album','album','running')`);
    await db.exec("set role service_role");
    const claimed = await db.query<{ status: string; worker_id: string }>(
      "select status,worker_id::text from public.claim_catalog_import_job($1,300,1)", [worker],
    );
    await db.exec("reset role");
    assert.deepEqual(claimed.rows, [{ status: "running", worker_id: worker }]);
    assert.deepEqual((await db.query("select status,error_message from public.catalog_import_items where job_id=1")).rows, [
      { status: "queued", error_message: "Przywrócono po przerwanym imporcie." },
    ]);
    await db.exec("set role anon");
    assert.equal((await db.query<{ count: string }>("select public.imported_album_count($1)::text as count", [alice])).rows[0].count, "2");
    await db.exec("reset role");

    await db.query("insert into public.artists(name,slug,spotify_id) values ('Gość','gosc','DDDDDDDDDDDDDDDDDDDDDD')");
    await db.query("insert into public.albums(title,slug,spotify_id) values ('Szkielet albumu','szkielet','EEEEEEEEEEEEEEEEEEEEEE')");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.exec("set role authenticated");
    await db.query("select public.submit_spotify_catalog_item('artist','DDDDDDDDDDDDDDDDDDDDDD','Gość',null,'PL','rock')");
    await db.query("select public.submit_spotify_catalog_item('album','EEEEEEEEEEEEEEEEEEEEEE','Szkielet albumu',null,'PL','pop')");
    await db.exec("reset role");
    assert.deepEqual((await db.query("select country_code from public.catalog_submissions where spotify_id='DDDDDDDDDDDDDDDDDDDDDD'")).rows, [{ country_code: "PL" }]);
    assert.equal((await db.query<{ count: number }>("select count(*)::integer as count from public.catalog_submissions where spotify_id in ('DDDDDDDDDDDDDDDDDDDDDD','EEEEEEEEEEEEEEEEEEEEEE')")).rows[0].count, 2);
    await db.query("update public.catalog_submissions set status='rejected', moderator_id=$1, rejection_reason='Duplikat' where spotify_id='DDDDDDDDDDDDDDDDDDDDDD'", [alice]);
    assert.deepEqual((await db.query("select action,rejection_reason from public.catalog_moderation_history")).rows, [
      { action: "rejected", rejection_reason: "Duplikat" },
    ]);

    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.exec("set role authenticated");
    await db.query("insert into public.want_to_listen(user_id,album_id) values ($1,1)", [alice]);
    await db.query("insert into public.ratings(user_id,album_id,rating) values ($1,1,8.5)", [alice]);
    await db.query("insert into public.artist_ratings(user_id,artist_id,rating) values ($1,1,8.5)", [alice]);
    await db.query("insert into public.comments(user_id,album_id,content) values ($1,1,'Świetny album')", [alice]);
    await db.query("insert into public.comments(user_id,album_id,parent_comment_id,content) values ($1,1,1,'Zgadzam się')", [alice]);
    await db.query("insert into public.user_feedback(user_id,category,message,page_url) values ($1,'bug','Nie działa przycisk','/album/album')", [alice]);
    await db.query("insert into public.ratings(user_id,album_id,rating) values ($1,1,9) on conflict (user_id,album_id) do update set rating=excluded.rating", [alice]);
    await db.query("update public.comments set content='Bardzo dobry album' where user_id=$1", [alice]);
    await db.query("update public.users set username='Alice_2' where id=$1", [alice]);
    await db.query("insert into storage.objects(bucket_id,name) values ('avatars',$1)", [`${alice}/avatar`]);
    assert.equal((await db.query("select * from public.listened")).rows.length, 1);
    assert.equal((await db.query("select * from public.want_to_listen")).rows.length, 0);
    assert.equal((await db.query<{ rating: string }>("select rating::text as rating from public.ratings")).rows[0].rating, "9.0");
    assert.deepEqual((await db.query("select average::text, rating_count from public.album_rating_summary")).rows, [{ average: "9.0", rating_count: 1 }]);
    assert.deepEqual((await db.query("select recent_rating_count,average::text,rating_count from public.recent_album_rating_summary")).rows, [{ recent_rating_count: 1, average: "9.0", rating_count: 1 }]);
    assert.deepEqual((await db.query("select average::text, rating_count from public.artist_rating_summary")).rows, [{ average: "8.5", rating_count: 1 }]);
    assert.deepEqual((await db.query("select average::text, rated_album_count from public.artist_album_rating_summary")).rows, [{ average: "9.0", rated_album_count: 1 }]);
    await assert.rejects(db.query("insert into public.ratings(user_id,album_id,rating) values ($1,1,9)", [bob]), /row-level security/);
    await assert.rejects(db.query("insert into public.artist_ratings(user_id,artist_id,rating) values ($1,1,9)", [bob]), /row-level security/);
    await assert.rejects(db.query("update public.users set role='admin' where id=$1", [alice]), /permission denied/);
    await assert.rejects(db.query("update public.comments set parent_comment_id=null where id=2"), /permission denied/);
    await assert.rejects(db.query("insert into public.comments(user_id,album_id,content) values ($1,1,'   ')", [alice]));
    await assert.rejects(db.query("insert into public.comment_likes(user_id,comment_id) values ($1,1)", [alice]), /row-level security/);
    await db.exec("reset role");

    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [bob]);
    await db.exec("set role authenticated");
    await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values ('avatars',$1)", [`${alice}/other`]), /row-level security/);
    await db.query("insert into storage.objects(bucket_id,name) values ('avatars',$1)", [`${bob}/avatar`]);
    await db.query("insert into public.comment_likes(user_id,comment_id) values ($1,1)", [bob]);
    await db.query("insert into public.comments(user_id,album_id,parent_comment_id,content) values ($1,1,1,'Odpowiedź Boba')", [bob]);
    await db.query("select public.report_comment(1,'other','Do sprawdzenia')");
    await assert.rejects(db.query("insert into public.comment_likes(user_id,comment_id) values ($1,1)", [bob]));
    await db.query("delete from public.comment_likes where user_id=$1", [alice]);
    assert.equal((await db.query("select * from public.comment_likes")).rows.length, 1);
    assert.equal((await db.query("select * from public.comment_reports")).rows.length, 1);
    assert.deepEqual((await db.query("select kind,comment_id from public.notifications where kind in ('comment_like','comment_reply')")).rows, []);
    assert.equal((await db.query("select * from public.user_feedback")).rows.length, 0);
    await db.exec("reset role");

    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.exec("set role authenticated");
    assert.deepEqual((await db.query("select kind from public.notifications where kind in ('comment_like','comment_reply') order by kind")).rows, [
      { kind: "comment_like" },
      { kind: "comment_reply" },
    ]);
    assert.equal((await db.query("select * from public.user_feedback")).rows.length, 1);
    await db.exec("reset role");

    await db.exec("set role anon");
    assert.equal((await db.query("select * from public.users")).rows.length, 2);
    assert.equal((await db.query("select * from public.ratings")).rows.length, 1);
    assert.equal((await db.query("select * from public.artist_ratings")).rows.length, 1);
    assert.equal((await db.query("select * from public.comments")).rows.length, 3);
    assert.equal((await db.query("select * from public.comment_likes")).rows.length, 1);
    assert.equal((await db.query("select * from public.listened")).rows.length, 1);
    assert.equal((await db.query("select * from storage.objects")).rows.length, 2);
    await db.exec("reset role");
  } finally {
    await db.close();
  }
});

test("community migration refuses to replace non-empty draft tables", async () => {
  const db = new PGlite();
  try {
    await db.exec(draftSchema);
    await db.exec("insert into public.users(id,username) values (1,'existing')");
    await assert.rejects(db.exec(migration), /requires the five draft tables to be empty/);
    await db.exec("rollback");
    assert.equal((await db.query("select username from public.users")).rows.length, 1);
  } finally {
    await db.close();
  }
});
