begin;

alter table public.artists
  add column biography_author_id uuid references public.users(id) on delete set null,
  add column biography_updated_at timestamptz;

create table public.artist_biography_submissions (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 80 and 5000),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'superseded')),
  rejection_reason text
    check (rejection_reason is null or char_length(btrim(rejection_reason)) between 1 and 1000),
  moderator_id uuid references public.users(id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status <> 'rejected' or rejection_reason is not null)
);

create unique index artist_biography_submissions_one_pending_idx
  on public.artist_biography_submissions (artist_id, user_id)
  where status = 'pending';
create index artist_biography_submissions_queue_idx
  on public.artist_biography_submissions (status, created_at);
create index artist_biography_submissions_author_idx
  on public.artist_biography_submissions (user_id, status);

create trigger artist_biography_submissions_set_updated_at
before update on public.artist_biography_submissions
for each row execute function public.set_updated_at();

alter table public.artist_biography_submissions enable row level security;

create policy artist_biography_submissions_read_own_or_admin
on public.artist_biography_submissions for select to authenticated
using ((select auth.uid()) = user_id or public.is_catalog_admin());

revoke all on public.artist_biography_submissions from public, anon, authenticated;
grant select on public.artist_biography_submissions to authenticated;

create or replace function public.submit_artist_biography(
  target_artist_id bigint,
  biography text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := (select auth.uid());
  normalized_biography text := btrim(biography);
  pending_id bigint;
begin
  if viewer_id is null or not public.is_active_user() then
    raise exception 'Authentication required';
  end if;
  if char_length(normalized_biography) not between 80 and 5000 then
    raise exception 'Biography length must be between 80 and 5000 characters';
  end if;
  if not exists (
    select 1 from public.artists
    where id = target_artist_id and catalog_visible = true
  ) then
    raise exception 'Artist is not available for biography submissions';
  end if;

  select id into pending_id
  from public.artist_biography_submissions
  where artist_id = target_artist_id and user_id = viewer_id and status = 'pending'
  for update;

  if pending_id is not null then
    update public.artist_biography_submissions
    set content = normalized_biography
    where id = pending_id;
    return pending_id;
  end if;

  if (
    select count(*) from public.artist_biography_submissions
    where user_id = viewer_id and created_at >= now() - interval '24 hours'
  ) >= 5 then
    raise exception 'Daily biography submission limit reached';
  end if;

  insert into public.artist_biography_submissions (artist_id, user_id, content)
  values (target_artist_id, viewer_id, normalized_biography)
  returning id into pending_id;
  return pending_id;
end;
$$;

create or replace function public.moderate_artist_biography(
  target_submission_id bigint,
  decision text,
  reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_id uuid := (select auth.uid());
  submission public.artist_biography_submissions%rowtype;
  normalized_reason text := nullif(btrim(reason), '');
begin
  if admin_id is null or not public.is_catalog_admin() then
    raise exception 'Administrator access required';
  end if;
  if decision not in ('approve', 'reject') then
    raise exception 'Invalid biography moderation decision';
  end if;
  if decision = 'reject' and normalized_reason is null then
    raise exception 'Rejection reason is required';
  end if;
  if normalized_reason is not null and char_length(normalized_reason) > 1000 then
    raise exception 'Rejection reason is too long';
  end if;

  select * into submission
  from public.artist_biography_submissions
  where id = target_submission_id and status = 'pending'
  for update;
  if not found then raise exception 'Pending biography submission not found'; end if;

  if decision = 'reject' then
    update public.artist_biography_submissions
    set status = 'rejected', rejection_reason = normalized_reason,
      moderator_id = admin_id, moderated_at = now()
    where id = submission.id;
    return;
  end if;

  update public.artist_biography_submissions
  set status = 'superseded'
  where artist_id = submission.artist_id and status = 'approved';

  update public.artist_biography_submissions
  set status = 'approved', rejection_reason = null,
    moderator_id = admin_id, moderated_at = now()
  where id = submission.id;

  update public.artists
  set description = submission.content,
    biography_author_id = submission.user_id,
    biography_updated_at = now(),
    enrichment_field_sources = coalesce(enrichment_field_sources, '{}'::jsonb) - 'description',
    updated_at = now()
  where id = submission.artist_id;
end;
$$;

create or replace function public.accepted_biography_count(profile_id uuid)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)
  from public.artist_biography_submissions
  where user_id = profile_id and status in ('approved', 'superseded');
$$;

revoke all on function public.submit_artist_biography(bigint,text) from public, anon;
grant execute on function public.submit_artist_biography(bigint,text) to authenticated;
revoke all on function public.moderate_artist_biography(bigint,text,text) from public, anon;
grant execute on function public.moderate_artist_biography(bigint,text,text) to authenticated;
revoke all on function public.accepted_biography_count(uuid) from public;
grant execute on function public.accepted_biography_count(uuid) to anon, authenticated;

notify pgrst, 'reload schema';
commit;
