begin;

create table public.user_list_ratings (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.user_lists(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  rating numeric(3,1) not null
    check (rating >= 1 and rating <= 10 and rating * 2 = floor(rating * 2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, list_id)
);

create index user_list_ratings_list_id_idx on public.user_list_ratings (list_id);

create trigger user_list_ratings_set_updated_at
before update on public.user_list_ratings
for each row execute function public.set_updated_at();

alter table public.user_list_ratings enable row level security;

create policy user_list_ratings_public_read on public.user_list_ratings
for select to anon, authenticated
using (exists (
  select 1 from public.user_lists list
  where list.id = user_list_ratings.list_id and list.is_public and list.kind = 'tracks'
));

create policy user_list_ratings_insert_own on public.user_list_ratings
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and public.is_active_user()
  and exists (
    select 1 from public.user_lists list
    where list.id = user_list_ratings.list_id
      and list.is_public
      and list.kind = 'tracks'
      and list.user_id <> (select auth.uid())
  )
);

create policy user_list_ratings_update_own on public.user_list_ratings
for update to authenticated
using (user_id = (select auth.uid()) and public.is_active_user())
with check (
  user_id = (select auth.uid())
  and public.is_active_user()
  and exists (
    select 1 from public.user_lists list
    where list.id = user_list_ratings.list_id
      and list.is_public
      and list.kind = 'tracks'
      and list.user_id <> (select auth.uid())
  )
);

create policy user_list_ratings_delete_own on public.user_list_ratings
for delete to authenticated
using (user_id = (select auth.uid()) and public.is_active_user());

revoke all on public.user_list_ratings from anon, authenticated;
grant select on public.user_list_ratings to anon, authenticated;
grant insert, update, delete on public.user_list_ratings to authenticated;
grant usage, select on sequence public.user_list_ratings_id_seq to authenticated;

create view public.user_list_rating_summary
with (security_invoker = true)
as
select
  list_id,
  round(avg(rating), 1) as average,
  count(*)::bigint as rating_count
from public.user_list_ratings
group by list_id;

grant select on public.user_list_rating_summary to anon, authenticated;

drop function public.latest_public_playlists(integer);
create function public.latest_public_playlists(limit_count integer default 12)
returns table (
  id bigint,
  name text,
  description text,
  cover_url text,
  created_at timestamptz,
  username text,
  track_count bigint,
  sample_cover_urls text[],
  average numeric,
  rating_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    list.id,
    list.name,
    list.description,
    list.cover_url,
    list.created_at,
    owner.username,
    (select count(*) from public.user_track_list_items item where item.list_id = list.id) as track_count,
    coalesce((
      select array_agg(sample.cover_url order by sample.first_position)
      from (
        select album.id, album.cover_url, min(item.position) as first_position
        from public.user_track_list_items item
        join public.tracks track on track.id = item.track_id
        join public.albums album on album.id = track.album_id
        where item.list_id = list.id and album.cover_url is not null
        group by album.id, album.cover_url
        order by min(item.position)
        limit 4
      ) sample
    ), '{}'::text[]) as sample_cover_urls,
    summary.average,
    coalesce(summary.rating_count, 0)::bigint as rating_count
  from public.user_lists list
  join public.users owner on owner.id = list.user_id
  left join public.user_list_rating_summary summary on summary.list_id = list.id
  where list.is_public and list.kind = 'tracks'
  order by list.created_at desc, list.id desc
  limit least(greatest(limit_count, 1), 30);
$$;

revoke all on function public.latest_public_playlists(integer) from public;
grant execute on function public.latest_public_playlists(integer) to anon, authenticated;

notify pgrst, 'reload schema';
commit;
