-- Matched against the live catalog schema on 2026-09-08 (see docs/database.md).
-- No catalog data is seeded. All DDL and function installation are transactional.
begin;

create table if not exists public.artists (
  id bigint generated by default as identity primary key, spotify_id text, name text not null,
  slug text not null unique, image_url text, description text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.albums (
  id bigint generated by default as identity primary key, spotify_id text,
  artist_id bigint not null references public.artists(id), title text not null,
  slug text not null unique, cover_url text, release_date date,
  album_type text not null check (album_type in ('album', 'ep')), description text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.tracks (
  id bigint generated by default as identity primary key, album_id bigint not null references public.albums(id),
  spotify_id text, title text not null, track_number integer not null check (track_number > 0),
  duration_ms integer not null check (duration_ms >= 0)
);

alter table public.albums add column if not exists release_date_raw text;
alter table public.albums add column if not exists release_date_precision text;
alter table public.tracks add column if not exists disc_number integer not null default 1;

-- Refuse incompatible existing column types rather than converting or replacing data.
do $$
begin
  if exists (
    select 1 from (values
      ('artists','id','bigint'), ('artists','spotify_id','text'), ('artists','name','text'),
      ('artists','slug','text'), ('artists','image_url','text'), ('artists','updated_at','timestamp with time zone'),
      ('albums','id','bigint'), ('albums','spotify_id','text'), ('albums','artist_id','bigint'),
      ('albums','title','text'), ('albums','slug','text'), ('albums','cover_url','text'),
      ('albums','release_date','date'), ('albums','album_type','text'),
      ('albums','release_date_raw','text'), ('albums','release_date_precision','text'),
      ('albums','updated_at','timestamp with time zone'),
      ('tracks','id','bigint'), ('tracks','album_id','bigint'), ('tracks','spotify_id','text'),
      ('tracks','title','text'), ('tracks','disc_number','integer'), ('tracks','track_number','integer'),
      ('tracks','duration_ms','integer')
    ) expected(tbl,col,typ)
    left join information_schema.columns actual on actual.table_schema='public'
      and actual.table_name=expected.tbl and actual.column_name=expected.col
    where actual.data_type is distinct from expected.typ
  ) then
    raise exception 'Existing schema differs from the importer contract; inspect and adapt migration first';
  end if;
end $$;

-- Do not silently remove pre-existing global track-ID uniqueness or one-disc keys.
-- Such constraints must be reviewed from the actual schema before deployment.
create unique index if not exists tapebase_artists_spotify_id on public.artists(spotify_id);
create unique index if not exists albums_spotify_id_key on public.albums(spotify_id);
create unique index if not exists tapebase_tracks_position on public.tracks(album_id,disc_number,track_number);

create table if not exists public.album_artists (
  album_id bigint not null references public.albums(id), artist_id bigint not null references public.artists(id),
  position integer not null check (position > 0), primary key (album_id,artist_id)
);
-- Existing track_artists stores editorial main/feature roles. Spotify does not
-- expose those roles: keep its ordered credits in a separate source table.
create table if not exists public.spotify_track_artists (
  track_id bigint not null references public.tracks(id), artist_id bigint not null references public.artists(id),
  position integer not null check (position > 0), primary key (track_id,artist_id)
);

do $$
begin
  if exists (
    select 1 from (values ('album_artists','album_id','bigint'), ('album_artists','artist_id','bigint'),
      ('album_artists','position','integer'), ('spotify_track_artists','track_id','bigint'),
      ('spotify_track_artists','artist_id','bigint'), ('spotify_track_artists','position','integer')) expected(tbl,col,typ)
    left join information_schema.columns actual on actual.table_schema='public'
      and actual.table_name=expected.tbl and actual.column_name=expected.col
    where actual.data_type is distinct from expected.typ
  ) then raise exception 'Existing credit tables differ from the importer contract'; end if;
end $$;

-- Public catalog reads; import credentials remain backend-only.
alter table public.artists enable row level security;
alter table public.albums enable row level security;
alter table public.tracks enable row level security;
alter table public.album_artists enable row level security;
alter table public.spotify_track_artists enable row level security;
do $$
declare tbl text; sequence_name text;
begin
  foreach tbl in array array['artists','albums','tracks','album_artists','spotify_track_artists'] loop
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=tbl and policyname='tapebase_catalog_read') then
      execute format('create policy tapebase_catalog_read on public.%I for select to anon, authenticated using (true)',tbl);
    end if;
    execute format('grant select on public.%I to anon, authenticated',tbl);
    execute format('grant select, insert, update, delete on public.%I to service_role',tbl);
  end loop;
  foreach tbl in array array['artists','albums','tracks'] loop
    sequence_name := pg_get_serial_sequence(format('public.%I',tbl),'id');
    if sequence_name is not null then
      execute format('grant usage, select on sequence %s to service_role',sequence_name);
    end if;
  end loop;
end $$;

create or replace function public.spotify_import_status()
returns jsonb language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object('version',1);
$$;
revoke all on function public.spotify_import_status() from public, anon, authenticated;
grant execute on function public.spotify_import_status() to service_role;

create or replace function public.import_spotify_catalog(payload jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  performer jsonb; release jsonb; song jsonb; credit record;
  performer_id bigint; release_id bigint; song_id bigint; primary_id bigint;
  raw_date text; date_precision text; full_date date;
  album_count integer := 0; track_count integer := 0; artists_count integer := 0;
begin
  if payload->>'version' is distinct from '1'
    or jsonb_typeof(payload->'artists') is distinct from 'array'
    or jsonb_typeof(payload->'albums') is distinct from 'array' then
    raise exception 'Invalid Spotify import envelope';
  end if;
  if jsonb_array_length(payload->'albums') not between 1 and 100
    or jsonb_array_length(payload->'artists') not between 1 and 10000 then
    raise exception 'Spotify import exceeds limits or is empty';
  end if;
  -- Serialize import transactions, including overlapping artists across albums.
  perform pg_advisory_xact_lock(724031906);
  if (select count(*) <> count(distinct item->>'spotify_id') from jsonb_array_elements(payload->'artists') item)
    or (select count(*) <> count(distinct item->>'spotify_id') from jsonb_array_elements(payload->'albums') item) then
    raise exception 'Duplicate or missing Spotify ID';
  end if;

  for performer in select value from jsonb_array_elements(payload->'artists') loop
    if coalesce(performer->>'spotify_id','') !~ '^[A-Za-z0-9]{22}$'
      or coalesce(btrim(performer->>'name'),'') = '' or coalesce(btrim(performer->>'slug'),'') = '' then
      raise exception 'Invalid artist';
    end if;
    insert into public.artists as existing (spotify_id,name,slug,image_url)
    values (performer->>'spotify_id',performer->>'name',performer->>'slug',performer->>'image_url')
    on conflict (spotify_id) do update set name=excluded.name,
      image_url=case when performer ? 'image_url' then excluded.image_url else existing.image_url end,
      updated_at=now();
    artists_count := artists_count + 1;
  end loop;

  for release in select value from jsonb_array_elements(payload->'albums') loop
    if coalesce(release->>'spotify_id','') !~ '^[A-Za-z0-9]{22}$'
      or coalesce(btrim(release->>'title'),'') = '' or coalesce(btrim(release->>'slug'),'') = ''
      or coalesce(release->>'album_type','') not in ('album','ep')
      or coalesce(release->>'spotify_album_type','') not in ('album','single')
      or (release->>'spotify_album_type'='single' and release->>'album_type'<>'ep')
      or jsonb_typeof(release->'artists') is distinct from 'array'
      or jsonb_typeof(release->'tracks') is distinct from 'array' then
      raise exception 'Invalid album or unconfirmed single';
    end if;
    if jsonb_array_length(release->'artists') < 1
      or jsonb_array_length(release->'tracks') < 1
      or jsonb_array_length(release->'tracks') is distinct from (release->>'total_tracks')::integer then
      raise exception 'Incomplete tracklist or missing album artists';
    end if;
    if (select count(*) <> count(distinct ((item->>'disc_number')::integer, (item->>'track_number')::integer))
        from jsonb_array_elements(release->'tracks') item) then
      raise exception 'Duplicate track position';
    end if;
    if (select count(*) <> count(distinct value) from jsonb_array_elements_text(release->'artists')) then
      raise exception 'Duplicate album credit';
    end if;
    raw_date := release->>'release_date_raw'; date_precision := release->>'release_date_precision';
    if date_precision='year' and raw_date ~ '^[0-9]{4}$' then
      full_date := (raw_date || '-01-01')::date;
    elsif date_precision='month' and raw_date ~ '^[0-9]{4}-[0-9]{2}$' then
      full_date := (raw_date || '-01')::date;
    elsif date_precision='day' and raw_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
      full_date := raw_date::date;
    else raise exception 'Invalid release date precision'; end if;
    if date_precision <> 'day' then full_date := null; end if;
    if (release->>'release_date')::date is distinct from full_date then raise exception 'Inconsistent release date'; end if;
    select id into primary_id from public.artists where spotify_id=release->'artists'->>0;
    if primary_id is null then raise exception 'Missing primary artist'; end if;
    insert into public.albums (spotify_id,artist_id,title,slug,cover_url,release_date,release_date_raw,release_date_precision,album_type)
    values (release->>'spotify_id',primary_id,release->>'title',release->>'slug',release->>'cover_url',
      full_date,raw_date,date_precision,release->>'album_type')
    on conflict (spotify_id) do update set artist_id=excluded.artist_id,title=excluded.title,
      cover_url=excluded.cover_url,release_date=excluded.release_date,release_date_raw=excluded.release_date_raw,
      release_date_precision=excluded.release_date_precision,album_type=excluded.album_type,updated_at=now()
    returning id into release_id;

    -- Never delete tracks with possible editorial/producer references. Reject a
    -- smaller/repositioned catalog until an operator reconciles it deliberately.
    if exists (select 1 from public.tracks existing where existing.album_id=release_id and not exists (
      select 1 from jsonb_array_elements(release->'tracks') incoming
      where (incoming->>'disc_number')::integer=existing.disc_number
        and (incoming->>'track_number')::integer=existing.track_number
    )) then raise exception 'Existing track positions disappeared; manual reconciliation required'; end if;
    if exists (select 1 from public.tracks existing, jsonb_array_elements(release->'tracks') incoming
      where existing.album_id=release_id
        and (incoming->>'disc_number')::integer=existing.disc_number
        and (incoming->>'track_number')::integer=existing.track_number
        and existing.spotify_id is not null and existing.spotify_id is distinct from incoming->>'spotify_id'
    ) then raise exception 'Track identity changed at an existing position; manual reconciliation required'; end if;

    for credit in select value, ordinality from jsonb_array_elements_text(release->'artists') with ordinality loop
      if not exists (select 1 from jsonb_array_elements(payload->'artists') item where item->>'spotify_id'=credit.value) then
        raise exception 'Album credit missing from payload';
      end if;
      select id into performer_id from public.artists where spotify_id=credit.value;
      insert into public.album_artists (album_id,artist_id,position) values (release_id,performer_id,credit.ordinality)
      on conflict (album_id,artist_id) do update set position=excluded.position;
    end loop;
    delete from public.album_artists existing where album_id=release_id and not exists (
      select 1 from public.artists a, jsonb_array_elements_text(release->'artists') incoming
      where a.id=existing.artist_id and a.spotify_id=incoming.value
    );

    for song in select value from jsonb_array_elements(release->'tracks') loop
      if coalesce(song->>'spotify_id','') !~ '^[A-Za-z0-9]{22}$' or coalesce(btrim(song->>'title'),'') = ''
        or coalesce((song->>'disc_number')::integer,0) < 1 or coalesce((song->>'track_number')::integer,0) < 1
        or coalesce((song->>'duration_ms')::integer,-1) < 0
        or jsonb_typeof(song->'artists') is distinct from 'array' then raise exception 'Invalid track'; end if;
      if jsonb_array_length(song->'artists') < 1 then raise exception 'Missing track artists'; end if;
      if (select count(*) <> count(distinct value) from jsonb_array_elements_text(song->'artists')) then
        raise exception 'Duplicate track credit';
      end if;
      insert into public.tracks (album_id,spotify_id,title,disc_number,track_number,duration_ms)
      values (release_id,song->>'spotify_id',song->>'title',(song->>'disc_number')::integer,
        (song->>'track_number')::integer,(song->>'duration_ms')::integer)
      on conflict (album_id,disc_number,track_number) do update set spotify_id=excluded.spotify_id,
        title=excluded.title,duration_ms=excluded.duration_ms returning id into song_id;
      for credit in select value, ordinality from jsonb_array_elements_text(song->'artists') with ordinality loop
        if not exists (select 1 from jsonb_array_elements(payload->'artists') item where item->>'spotify_id'=credit.value) then
          raise exception 'Track credit missing from payload';
        end if;
        select id into performer_id from public.artists where spotify_id=credit.value;
        insert into public.spotify_track_artists (track_id,artist_id,position) values (song_id,performer_id,credit.ordinality)
        on conflict (track_id,artist_id) do update set position=excluded.position;
      end loop;
      delete from public.spotify_track_artists existing where track_id=song_id and not exists (
        select 1 from public.artists a, jsonb_array_elements_text(song->'artists') incoming
        where a.id=existing.artist_id and a.spotify_id=incoming.value
      );
      track_count := track_count + 1;
      if track_count > 10000 then raise exception 'Too many tracks'; end if;
    end loop;
    album_count := album_count + 1;
  end loop;
  return jsonb_build_object('version',1,'artists',artists_count,'albums',album_count,'tracks',track_count);
end;
$$;
revoke all on function public.import_spotify_catalog(jsonb) from public, anon, authenticated;
grant execute on function public.import_spotify_catalog(jsonb) to service_role;

notify pgrst, 'reload schema';
commit;
