begin;

create table public.concerts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  starts_at timestamptz not null,
  start_time_known boolean not null default true,
  ends_at timestamptz,
  timezone text,
  status text not null default 'scheduled' check (status in ('scheduled','cancelled','postponed','rescheduled')),
  venue_name text not null check (char_length(btrim(venue_name)) between 1 and 300),
  city text not null check (char_length(btrim(city)) between 1 and 200),
  country_code text not null default 'PL' check (country_code ~ '^[A-Z]{2}$'),
  latitude numeric(9,6),
  longitude numeric(9,6),
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);
create index concerts_upcoming_idx on public.concerts(starts_at, id) where status <> 'cancelled';
create trigger concerts_set_updated_at before update on public.concerts
for each row execute function public.set_updated_at();

create table public.concert_artists (
  concert_id bigint not null references public.concerts(id) on delete cascade,
  artist_id bigint not null references public.artists(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  primary key (concert_id, artist_id)
);
create index concert_artists_artist_idx on public.concert_artists(artist_id, concert_id);

create table public.concert_sources (
  id bigint generated by default as identity primary key,
  concert_id bigint not null references public.concerts(id) on delete cascade,
  source text not null check (source in ('ticketmaster')),
  external_id text not null check (char_length(external_id) between 1 and 200),
  source_url text,
  last_seen_at timestamptz not null default now(),
  raw_status text,
  unique (source, external_id)
);
create index concert_sources_concert_idx on public.concert_sources(concert_id);

create table public.artist_event_sources (
  artist_id bigint not null references public.artists(id) on delete cascade,
  source text not null check (source in ('ticketmaster')),
  external_artist_id text not null check (char_length(external_artist_id) between 1 and 200),
  matched_name text not null,
  updated_at timestamptz not null default now(),
  primary key (artist_id, source),
  unique (source, external_artist_id)
);

create table public.ticket_offers (
  id bigint generated by default as identity primary key,
  concert_id bigint not null references public.concerts(id) on delete cascade,
  provider text not null check (provider in ('ticketmaster')),
  external_id text not null check (char_length(external_id) between 1 and 200),
  url text not null check (url ~ '^https://'),
  status text not null default 'unknown' check (status in ('onsale','offsale','cancelled','postponed','rescheduled','unknown')),
  price_min numeric(10,2),
  price_max numeric(10,2),
  currency text check (currency is null or currency ~ '^[A-Z]{3}$'),
  last_checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_id),
  check (price_min is null or price_min >= 0),
  check (price_max is null or price_max >= coalesce(price_min, 0))
);
create index ticket_offers_concert_idx on public.ticket_offers(concert_id);
create trigger ticket_offers_set_updated_at before update on public.ticket_offers
for each row execute function public.set_updated_at();

create table public.concert_sync_state (
  id boolean primary key default true check (id),
  last_artist_id bigint not null default 0,
  last_completed_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);
insert into public.concert_sync_state(id) values (true);

create table public.concert_sync_runs (
  id bigint generated by default as identity primary key,
  started_by uuid references public.users(id) on delete set null,
  status text not null default 'running' check (status in ('running','completed','failed')),
  artists_checked integer not null default 0,
  events_found integer not null default 0,
  events_saved integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index concert_sync_runs_started_idx on public.concert_sync_runs(started_at desc);
create unique index concert_sync_runs_one_running_idx on public.concert_sync_runs((true)) where status = 'running';

alter table public.concerts enable row level security;
alter table public.concert_artists enable row level security;
alter table public.concert_sources enable row level security;
alter table public.artist_event_sources enable row level security;
alter table public.ticket_offers enable row level security;
alter table public.concert_sync_state enable row level security;
alter table public.concert_sync_runs enable row level security;

create policy concerts_public_read on public.concerts for select to anon, authenticated using (true);
create policy concert_artists_public_read on public.concert_artists for select to anon, authenticated using (true);
create policy ticket_offers_public_read on public.ticket_offers for select to anon, authenticated using (true);
create policy concert_sources_admin_read on public.concert_sources for select to authenticated using (public.is_catalog_admin());
create policy artist_event_sources_admin_read on public.artist_event_sources for select to authenticated using (public.is_catalog_admin());
create policy concert_sync_state_admin_read on public.concert_sync_state for select to authenticated using (public.is_catalog_admin());
create policy concert_sync_runs_admin_read on public.concert_sync_runs for select to authenticated using (public.is_catalog_admin());

revoke all on public.concerts, public.concert_artists, public.concert_sources,
  public.artist_event_sources, public.ticket_offers, public.concert_sync_state,
  public.concert_sync_runs from anon, authenticated;
grant select on public.concerts, public.concert_artists, public.ticket_offers to anon, authenticated;
grant select on public.concert_sources, public.artist_event_sources,
  public.concert_sync_state, public.concert_sync_runs to authenticated;

notify pgrst, 'reload schema';
commit;
