begin;

create table public.catalog_submissions (
  id bigint generated by default as identity primary key,
  spotify_type text not null check (spotify_type in ('artist', 'album')),
  spotify_id text not null check (spotify_id ~ '^[A-Za-z0-9]{22}$'),
  spotify_url text not null,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  thumbnail_url text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'imported')),
  moderator_id uuid references public.users(id) on delete set null,
  moderator_note text check (moderator_note is null or char_length(moderator_note) <= 1000),
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (spotify_type, spotify_id),
  check (spotify_url = 'https://open.spotify.com/' || spotify_type || '/' || spotify_id),
  check (thumbnail_url is null or thumbnail_url ~ '^https://i\.scdn\.co/')
);

create table public.catalog_submission_supporters (
  submission_id bigint not null references public.catalog_submissions(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (submission_id, user_id)
);

create index catalog_submissions_queue_idx
  on public.catalog_submissions (status, created_at);
create index catalog_submission_supporters_user_idx
  on public.catalog_submission_supporters (user_id, created_at desc);

create trigger catalog_submissions_set_updated_at
before update on public.catalog_submissions
for each row execute function public.set_updated_at();

alter table public.catalog_submissions enable row level security;
alter table public.catalog_submission_supporters enable row level security;

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.users
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create policy catalog_submissions_read_supported_or_admin
on public.catalog_submissions for select to authenticated
using (
  public.is_catalog_admin()
  or exists (
    select 1 from public.catalog_submission_supporters supporter
    where supporter.submission_id = id
      and supporter.user_id = (select auth.uid())
  )
);

create policy catalog_submissions_admin_update
on public.catalog_submissions for update to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

create policy catalog_supporters_read_own_or_admin
on public.catalog_submission_supporters for select to authenticated
using (user_id = (select auth.uid()) or public.is_catalog_admin());

create or replace function public.submit_spotify_catalog_item(
  item_type text,
  item_id text,
  item_title text,
  item_thumbnail_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := (select auth.uid());
  v_submission_id bigint;
  already_supported boolean;
begin
  if viewer_id is null then raise exception 'Authentication required'; end if;
  if item_type not in ('artist', 'album') or item_id !~ '^[A-Za-z0-9]{22}$'
    or char_length(btrim(item_title)) not between 1 and 300
    or (item_thumbnail_url is not null and item_thumbnail_url !~ '^https://i\.scdn\.co/') then
    raise exception 'Invalid Spotify submission';
  end if;
  if (item_type = 'artist' and exists (select 1 from public.artists where spotify_id = item_id))
    or (item_type = 'album' and exists (select 1 from public.albums where spotify_id = item_id)) then
    raise exception 'Catalog item already exists';
  end if;

  insert into public.catalog_submissions (spotify_type, spotify_id, spotify_url, title, thumbnail_url)
  values (item_type, item_id, 'https://open.spotify.com/' || item_type || '/' || item_id,
    btrim(item_title), item_thumbnail_url)
  on conflict (spotify_type, spotify_id) do update set
    title = excluded.title,
    thumbnail_url = coalesce(excluded.thumbnail_url, public.catalog_submissions.thumbnail_url)
  returning id into v_submission_id;

  select exists (
    select 1 from public.catalog_submission_supporters
    where catalog_submission_supporters.submission_id = v_submission_id and user_id = viewer_id
  ) into already_supported;

  if not already_supported and (
    select count(*) from public.catalog_submission_supporters
    where user_id = viewer_id and created_at >= now() - interval '24 hours'
  ) >= 10 then
    raise exception 'Daily submission limit reached';
  end if;

  insert into public.catalog_submission_supporters (submission_id, user_id)
  values (v_submission_id, viewer_id)
  on conflict do nothing;

  return jsonb_build_object('id', v_submission_id, 'already_supported', already_supported);
end;
$$;

revoke all on public.catalog_submissions, public.catalog_submission_supporters from anon, authenticated;
grant select on public.catalog_submissions, public.catalog_submission_supporters to authenticated;
grant update (status, moderator_id, moderator_note, moderated_at) on public.catalog_submissions to authenticated;
revoke all on function public.is_catalog_admin() from public, anon;
grant execute on function public.is_catalog_admin() to authenticated;
revoke all on function public.submit_spotify_catalog_item(text,text,text,text) from public, anon;
grant execute on function public.submit_spotify_catalog_item(text,text,text,text) to authenticated;

notify pgrst, 'reload schema';
commit;
