begin;

create table public.youtube_channels (
  youtube_channel_id text primary key
    check (youtube_channel_id ~ '^UC[A-Za-z0-9_-]{22}$'),
  title text not null check (char_length(btrim(title)) between 1 and 300),
  thumbnail_url text,
  uploads_playlist_id text,
  channel_type text not null default 'unknown'
    check (channel_type in ('artist', 'label', 'vevo', 'publisher', 'unknown')),
  verification_status text not null default 'candidate'
    check (verification_status in ('candidate', 'verified', 'rejected')),
  last_refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.artist_youtube_channels (
  artist_id bigint not null references public.artists(id) on delete cascade,
  youtube_channel_id text not null references public.youtube_channels(youtube_channel_id) on delete cascade,
  match_method text not null
    check (match_method in ('wikidata', 'youtube_search', 'manual')),
  confidence_score double precision not null default 0
    check (confidence_score between 0 and 1),
  match_evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(match_evidence) = 'object'),
  status text not null default 'candidate'
    check (status in ('candidate', 'verified', 'rejected')),
  reviewed_by uuid references public.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (artist_id, youtube_channel_id)
);

create table public.youtube_videos (
  id bigint generated by default as identity primary key,
  youtube_video_id text not null unique
    check (youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'),
  youtube_channel_id text not null references public.youtube_channels(youtube_channel_id) on delete restrict,
  title text not null check (char_length(btrim(title)) between 1 and 500),
  thumbnail_url text,
  channel_title text not null check (char_length(btrim(channel_title)) between 1 and 300),
  view_count bigint not null default 0 check (view_count >= 0),
  published_at timestamptz,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  is_embeddable boolean not null default false,
  availability_status text not null default 'available'
    check (availability_status in ('available', 'unavailable')),
  last_refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.artist_videos (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  youtube_video_id text not null references public.youtube_videos(youtube_video_id) on delete cascade,
  matched_track_id bigint references public.tracks(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  is_official boolean not null default false,
  confidence_score double precision not null default 0
    check (confidence_score between 0 and 1),
  match_evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(match_evidence) = 'object'),
  reviewed_by uuid references public.users(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text
    check (rejection_reason is null or char_length(btrim(rejection_reason)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (artist_id, youtube_video_id),
  check (status <> 'rejected' or rejection_reason is not null)
);

create index artist_videos_public_idx
  on public.artist_videos(artist_id, status, youtube_video_id);
create index artist_videos_review_idx
  on public.artist_videos(status, created_at desc);
create index youtube_videos_popular_idx
  on public.youtube_videos(view_count desc, published_at desc)
  where availability_status = 'available' and is_embeddable = true;
create index artist_youtube_channels_review_idx
  on public.artist_youtube_channels(status, created_at desc);

create table public.artist_youtube_sync (
  artist_id bigint primary key references public.artists(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'completed', 'failed')),
  next_search_at timestamptz not null default now(),
  last_search_at timestamptz,
  last_stats_at timestamptz,
  locked_until timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);
create index artist_youtube_sync_queue_idx
  on public.artist_youtube_sync(next_search_at, artist_id)
  where status in ('pending', 'completed', 'failed');

create table public.youtube_sync_daily_usage (
  usage_date date primary key,
  search_calls integer not null default 0 check (search_calls >= 0),
  updated_at timestamptz not null default now()
);

create table public.youtube_sync_runs (
  id bigint generated by default as identity primary key,
  started_by uuid references public.users(id) on delete set null,
  status text not null default 'running'
    check (status in ('running', 'completed', 'failed')),
  artists_checked integer not null default 0,
  search_calls integer not null default 0,
  videos_found integer not null default 0,
  videos_saved integer not null default 0,
  videos_auto_approved integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index youtube_sync_runs_started_idx on public.youtube_sync_runs(started_at desc);
create unique index youtube_sync_runs_one_running_idx
  on public.youtube_sync_runs((true)) where status = 'running';

create trigger youtube_channels_set_updated_at before update on public.youtube_channels
for each row execute function public.set_updated_at();
create trigger artist_youtube_channels_set_updated_at before update on public.artist_youtube_channels
for each row execute function public.set_updated_at();
create trigger youtube_videos_set_updated_at before update on public.youtube_videos
for each row execute function public.set_updated_at();
create trigger artist_videos_set_updated_at before update on public.artist_videos
for each row execute function public.set_updated_at();
create trigger artist_youtube_sync_set_updated_at before update on public.artist_youtube_sync
for each row execute function public.set_updated_at();

create or replace function public.queue_artist_youtube_sync()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.catalog_visible = true and new.spotify_id is not null then
    insert into public.artist_youtube_sync(artist_id)
    values (new.id)
    on conflict (artist_id) do nothing;
  end if;
  return new;
end;
$$;

create trigger artists_queue_youtube_sync
after insert or update of catalog_visible, spotify_id on public.artists
for each row execute function public.queue_artist_youtube_sync();

insert into public.artist_youtube_sync(artist_id)
select id from public.artists
where catalog_visible = true and spotify_id is not null
on conflict (artist_id) do nothing;

create or replace function public.reserve_youtube_search_quota(
  requested_calls integer default 1,
  daily_limit integer default 50
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if requested_calls < 1 or requested_calls > 10
    or daily_limit < 1 or daily_limit > 100 then
    raise exception 'Invalid YouTube quota reservation';
  end if;

  insert into public.youtube_sync_daily_usage(usage_date, search_calls)
  values ((now() at time zone 'UTC')::date, requested_calls)
  on conflict (usage_date) do nothing;
  if found then return true; end if;

  update public.youtube_sync_daily_usage
  set search_calls = search_calls + requested_calls, updated_at = now()
  where usage_date = (now() at time zone 'UTC')::date
    and search_calls + requested_calls <= daily_limit;
  return found;
end;
$$;

create or replace function public.artist_videos_for_profile(
  target_artist_id bigint,
  result_limit integer default 5
)
returns table (
  youtube_video_id text,
  title text,
  thumbnail_url text,
  channel_title text,
  view_count bigint,
  published_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select video.youtube_video_id, video.title, video.thumbnail_url,
    video.channel_title, video.view_count, video.published_at
  from public.artist_videos relation
  join public.youtube_videos video
    on video.youtube_video_id = relation.youtube_video_id
  where relation.artist_id = target_artist_id
    and relation.status = 'approved'
    and video.availability_status = 'available'
    and video.is_embeddable = true
    and video.last_refreshed_at >= now() - interval '30 days'
  order by video.view_count desc, video.published_at desc nulls last, video.youtube_video_id
  limit least(greatest(coalesce(result_limit, 5), 1), 5);
$$;

create or replace function public.review_artist_youtube_video(
  target_artist_id bigint,
  target_youtube_video_id text,
  decision text,
  official boolean default false,
  reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_id uuid := (select auth.uid());
  normalized_reason text := nullif(btrim(reason), '');
begin
  if admin_id is null or not public.is_catalog_admin() then
    raise exception 'Administrator access required';
  end if;
  if decision not in ('approve', 'reject') then
    raise exception 'Invalid video moderation decision';
  end if;
  if decision = 'reject' and normalized_reason is null then
    raise exception 'Rejection reason is required';
  end if;
  if normalized_reason is not null and char_length(normalized_reason) > 1000 then
    raise exception 'Rejection reason is too long';
  end if;

  update public.artist_videos
  set status = case when decision = 'approve' then 'approved' else 'rejected' end,
    is_official = case when decision = 'approve' then official else false end,
    rejection_reason = case when decision = 'reject' then normalized_reason else null end,
    reviewed_by = admin_id,
    reviewed_at = now()
  where artist_id = target_artist_id
    and youtube_video_id = target_youtube_video_id;
  if not found then raise exception 'Video candidate not found'; end if;
end;
$$;

create or replace function public.review_artist_youtube_channel(
  target_artist_id bigint,
  target_youtube_channel_id text,
  decision text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_id uuid := (select auth.uid());
begin
  if admin_id is null or not public.is_catalog_admin() then
    raise exception 'Administrator access required';
  end if;
  if decision not in ('verify', 'reject') then
    raise exception 'Invalid channel moderation decision';
  end if;

  update public.artist_youtube_channels
  set status = case when decision = 'verify' then 'verified' else 'rejected' end,
    reviewed_by = admin_id,
    reviewed_at = now()
  where artist_id = target_artist_id
    and youtube_channel_id = target_youtube_channel_id;
  if not found then raise exception 'Channel candidate not found'; end if;

  if decision = 'verify' then
    update public.youtube_channels
    set verification_status = 'verified'
    where youtube_channel_id = target_youtube_channel_id;
    update public.artist_youtube_sync
    set status = 'pending', next_search_at = now(), last_error = null
    where artist_id = target_artist_id;
  end if;
end;
$$;

alter table public.youtube_channels enable row level security;
alter table public.artist_youtube_channels enable row level security;
alter table public.youtube_videos enable row level security;
alter table public.artist_videos enable row level security;
alter table public.artist_youtube_sync enable row level security;
alter table public.youtube_sync_daily_usage enable row level security;
alter table public.youtube_sync_runs enable row level security;

create policy youtube_channels_admin_read on public.youtube_channels
for select to authenticated using (public.is_catalog_admin());
create policy artist_youtube_channels_admin_read on public.artist_youtube_channels
for select to authenticated using (public.is_catalog_admin());
create policy youtube_videos_admin_read on public.youtube_videos
for select to authenticated using (public.is_catalog_admin());
create policy artist_videos_admin_read on public.artist_videos
for select to authenticated using (public.is_catalog_admin());
create policy artist_youtube_sync_admin_read on public.artist_youtube_sync
for select to authenticated using (public.is_catalog_admin());
create policy youtube_sync_daily_usage_admin_read on public.youtube_sync_daily_usage
for select to authenticated using (public.is_catalog_admin());
create policy youtube_sync_runs_admin_read on public.youtube_sync_runs
for select to authenticated using (public.is_catalog_admin());

revoke all on public.youtube_channels, public.artist_youtube_channels,
  public.youtube_videos, public.artist_videos, public.artist_youtube_sync,
  public.youtube_sync_daily_usage, public.youtube_sync_runs
from public, anon, authenticated;
grant select on public.youtube_channels, public.artist_youtube_channels,
  public.youtube_videos, public.artist_videos, public.artist_youtube_sync,
  public.youtube_sync_daily_usage, public.youtube_sync_runs
to authenticated;
grant all on public.youtube_channels, public.artist_youtube_channels,
  public.youtube_videos, public.artist_videos, public.artist_youtube_sync,
  public.youtube_sync_daily_usage, public.youtube_sync_runs
to service_role;
grant usage, select on sequence public.youtube_videos_id_seq,
  public.artist_videos_id_seq, public.youtube_sync_runs_id_seq
to service_role;

revoke all on function public.reserve_youtube_search_quota(integer,integer)
from public, anon, authenticated;
grant execute on function public.reserve_youtube_search_quota(integer,integer)
to service_role;
revoke all on function public.artist_videos_for_profile(bigint,integer) from public;
grant execute on function public.artist_videos_for_profile(bigint,integer)
to anon, authenticated;
revoke all on function public.review_artist_youtube_video(bigint,text,text,boolean,text)
from public, anon;
grant execute on function public.review_artist_youtube_video(bigint,text,text,boolean,text)
to authenticated;
revoke all on function public.review_artist_youtube_channel(bigint,text,text)
from public, anon;
grant execute on function public.review_artist_youtube_channel(bigint,text,text)
to authenticated;

notify pgrst, 'reload schema';
commit;
