begin;

create table public.artist_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  artist_id bigint not null references public.artists(id) on delete cascade,
  rating numeric(3,1) not null
    check (rating >= 1 and rating <= 10 and rating * 2 = floor(rating * 2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, artist_id)
);

create index artist_ratings_artist_id_idx on public.artist_ratings (artist_id);

create trigger artist_ratings_set_updated_at
before update on public.artist_ratings
for each row execute function public.set_updated_at();

alter table public.artist_ratings enable row level security;

create policy artist_ratings_public_read on public.artist_ratings
for select to anon, authenticated using (true);
create policy artist_ratings_insert_own on public.artist_ratings
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy artist_ratings_update_own on public.artist_ratings
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy artist_ratings_delete_own on public.artist_ratings
for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.artist_ratings from anon, authenticated;
grant select on public.artist_ratings to anon, authenticated;
grant insert, update, delete on public.artist_ratings to authenticated;
grant usage, select on sequence public.artist_ratings_id_seq to authenticated;

create view public.artist_rating_summary
with (security_invoker = true)
as
select
  artist_id,
  round(avg(rating), 1) as average,
  count(*)::bigint as rating_count
from public.artist_ratings
group by artist_id;

create view public.artist_album_rating_summary
with (security_invoker = true)
as
select
  album_artists.artist_id,
  round(avg(album_rating_summary.average), 1) as average,
  count(*)::bigint as rated_album_count
from public.album_artists
join public.album_rating_summary
  on album_rating_summary.album_id = album_artists.album_id
group by album_artists.artist_id;

grant select on public.artist_rating_summary,
  public.artist_album_rating_summary to anon, authenticated;

commit;
