begin;

-- The original community tables were only a draft: their bigint user IDs cannot
-- reference Supabase Auth UUIDs. Refuse to replace them if somebody starts using
-- them before this migration is applied.
do $$
begin
  if (select count(*) from public.users) > 0
    or (select count(*) from public.ratings) > 0
    or (select count(*) from public.comments) > 0
    or (select count(*) from public.listened) > 0
    or (select count(*) from public.want_to_listen) > 0 then
    raise exception 'Community migration requires the five draft tables to be empty';
  end if;
end
$$;

drop table public.comments;
drop table public.ratings;
drop table public.listened;
drop table public.want_to_listen;
drop table public.users;

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text,
  role text not null default 'user'
    check (role in ('user', 'admin', 'verified_artist', 'verified_producer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_username_format_check
    check (username ~ '^[A-Za-z0-9_]{3,24}$')
);

create unique index users_username_lower_key on public.users (lower(username));

create table public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  rating numeric(3,1) not null
    check (rating >= 1 and rating <= 10 and rating * 2 = floor(rating * 2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, album_id)
);

create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.listened (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, album_id)
);

create table public.want_to_listen (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, album_id)
);

create index ratings_album_id_idx on public.ratings (album_id);
create index comments_album_created_idx on public.comments (album_id, created_at desc);
create index listened_album_id_idx on public.listened (album_id);
create index want_to_listen_album_id_idx on public.want_to_listen (album_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger ratings_set_updated_at
before update on public.ratings
for each row execute function public.set_updated_at();

create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text := nullif(btrim(new.raw_user_meta_data ->> 'username'), '');
begin
  if requested_username is null
    or requested_username !~ '^[A-Za-z0-9_]{3,24}$' then
    requested_username := 'user_' || left(replace(new.id::text, '-', ''), 12);
  end if;

  insert into public.users (id, username)
  values (new.id, requested_username);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.mark_rated_album_listened()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.listened (user_id, album_id)
  values (new.user_id, new.album_id)
  on conflict (user_id, album_id) do nothing;
  return new;
end;
$$;

create trigger ratings_mark_album_listened
after insert or update of rating on public.ratings
for each row execute function public.mark_rated_album_listened();

create or replace function public.remove_listened_album_from_wishlist()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.want_to_listen
  where user_id = new.user_id and album_id = new.album_id;
  return new;
end;
$$;

create trigger listened_remove_from_wishlist
after insert on public.listened
for each row execute function public.remove_listened_album_from_wishlist();

alter table public.users enable row level security;
alter table public.ratings enable row level security;
alter table public.comments enable row level security;
alter table public.listened enable row level security;
alter table public.want_to_listen enable row level security;

create policy users_public_read on public.users
for select to anon, authenticated using (true);
create policy users_update_own on public.users
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy ratings_public_read on public.ratings
for select to anon, authenticated using (true);
create policy ratings_insert_own on public.ratings
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy ratings_update_own on public.ratings
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy ratings_delete_own on public.ratings
for delete to authenticated using ((select auth.uid()) = user_id);

create policy comments_public_read on public.comments
for select to anon, authenticated using (true);
create policy comments_insert_own on public.comments
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy comments_update_own on public.comments
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy comments_delete_own on public.comments
for delete to authenticated using ((select auth.uid()) = user_id);

create policy listened_read_own on public.listened
for select to authenticated using ((select auth.uid()) = user_id);
create policy listened_insert_own on public.listened
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy listened_delete_own on public.listened
for delete to authenticated using ((select auth.uid()) = user_id);

create policy want_to_listen_read_own on public.want_to_listen
for select to authenticated using ((select auth.uid()) = user_id);
create policy want_to_listen_insert_own on public.want_to_listen
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy want_to_listen_delete_own on public.want_to_listen
for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.users, public.ratings, public.comments,
  public.listened, public.want_to_listen from anon, authenticated;
grant select on public.users, public.ratings, public.comments to anon, authenticated;
grant update (username, avatar_url) on public.users to authenticated;
grant insert, update, delete on public.ratings, public.comments to authenticated;
grant select, insert, delete on public.listened, public.want_to_listen to authenticated;
grant usage, select on sequence public.ratings_id_seq, public.comments_id_seq,
  public.listened_id_seq, public.want_to_listen_id_seq to authenticated;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
revoke all on function public.mark_rated_album_listened() from public, anon, authenticated;
revoke all on function public.remove_listened_album_from_wishlist() from public, anon, authenticated;

commit;
