begin;

alter table public.catalog_submissions
  add column release_kind text,
  add column rejection_reason text;

update public.catalog_submissions set release_kind = 'album' where spotify_type = 'album';
update public.catalog_submissions
set rejection_reason = coalesce(nullif(btrim(moderator_note), ''), 'Brak podanego powodu — decyzja sprzed wdrożenia historii.')
where status = 'rejected';

alter table public.catalog_submissions
  add constraint catalog_submissions_release_kind_check check (
    (spotify_type = 'artist' and release_kind is null)
    or (spotify_type = 'album' and release_kind in ('album', 'ep'))
  ),
  add constraint catalog_submissions_rejection_reason_check check (
    rejection_reason is null or char_length(btrim(rejection_reason)) between 1 and 1000
  ),
  add constraint catalog_submissions_rejected_reason_required check (
    status <> 'rejected' or rejection_reason is not null
  );

create table public.catalog_moderation_history (
  id bigint generated by default as identity primary key,
  submission_id bigint references public.catalog_submissions(id) on delete set null,
  spotify_type text not null check (spotify_type in ('artist', 'album')),
  spotify_id text not null,
  title text not null,
  admin_id uuid references public.users(id) on delete set null,
  action text not null check (action in ('approved', 'rejected', 'imported', 'release_kind_changed')),
  previous_status text not null,
  new_status text not null,
  release_kind text check (release_kind in ('album', 'ep')),
  moderator_note text,
  rejection_reason text,
  created_at timestamptz not null default now()
);

create index catalog_moderation_history_created_idx
  on public.catalog_moderation_history(created_at desc);

alter table public.catalog_moderation_history enable row level security;
create policy catalog_moderation_history_admin_read
  on public.catalog_moderation_history for select to authenticated
  using (public.is_catalog_admin());
revoke all on public.catalog_moderation_history from anon, authenticated;
grant select on public.catalog_moderation_history to authenticated;

create or replace function public.record_catalog_moderation()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  history_action text;
begin
  if new.status is distinct from old.status and new.status in ('approved', 'rejected', 'imported') then
    history_action := new.status;
  elsif new.release_kind is distinct from old.release_kind then
    history_action := 'release_kind_changed';
  else
    return new;
  end if;

  insert into public.catalog_moderation_history (
    submission_id, spotify_type, spotify_id, title, admin_id, action,
    previous_status, new_status, release_kind, moderator_note, rejection_reason
  ) values (
    new.id, new.spotify_type, new.spotify_id, new.title, new.moderator_id,
    history_action, old.status, new.status, new.release_kind,
    new.moderator_note, new.rejection_reason
  );
  return new;
end;
$$;

create trigger catalog_submissions_record_moderation
after update of status, release_kind on public.catalog_submissions
for each row execute function public.record_catalog_moderation();

create or replace function public.queue_approved_submission()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status = 'approved' and (
    old.status is distinct from new.status or old.release_kind is distinct from new.release_kind
  ) then
    insert into public.catalog_import_jobs (submission_id, spotify_type, spotify_id, title, release_kind)
    values (new.id, new.spotify_type, new.spotify_id, new.title, new.release_kind)
    on conflict (submission_id) do update set
      release_kind = excluded.release_kind,
      status = case when public.catalog_import_jobs.status in ('completed','completed_with_errors')
        then public.catalog_import_jobs.status else 'queued' end,
      error_message = null;
  end if;
  return new;
end;
$$;

drop trigger catalog_submissions_queue_after_approval on public.catalog_submissions;
create trigger catalog_submissions_queue_after_approval
after update of status, release_kind on public.catalog_submissions
for each row execute function public.queue_approved_submission();

update public.catalog_import_jobs job
set release_kind = submission.release_kind
from public.catalog_submissions submission
where submission.id = job.submission_id and submission.spotify_type = 'album';

grant update (status, moderator_id, moderator_note, moderated_at, release_kind, rejection_reason)
  on public.catalog_submissions to authenticated;
revoke all on function public.record_catalog_moderation() from public, anon, authenticated;

notify pgrst, 'reload schema';
commit;
