begin;

create table public.catalog_import_jobs (
  id bigint generated by default as identity primary key,
  submission_id bigint not null unique references public.catalog_submissions(id) on delete cascade,
  spotify_type text not null check (spotify_type in ('artist', 'album')),
  spotify_id text not null check (spotify_id ~ '^[A-Za-z0-9]{22}$'),
  title text not null,
  market text not null default 'PL' check (market ~ '^[A-Z]{2}$'),
  release_kind text check (release_kind in ('album', 'ep')),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'waiting_quota', 'completed', 'completed_with_errors', 'failed')),
  albums_total integer not null default 0 check (albums_total >= 0),
  albums_completed integer not null default 0 check (albums_completed >= 0 and albums_completed <= albums_total),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table public.catalog_import_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.catalog_import_jobs(id) on delete cascade,
  spotify_album_id text not null check (spotify_album_id ~ '^[A-Za-z0-9]{22}$'),
  title text not null,
  album_type text not null check (album_type in ('album', 'ep')),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'completed', 'failed')),
  album_id bigint references public.albums(id) on delete set null,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, spotify_album_id)
);

create index catalog_import_jobs_status_idx on public.catalog_import_jobs(status, created_at);
create index catalog_import_items_job_status_idx on public.catalog_import_items(job_id, status, id);
create trigger catalog_import_jobs_set_updated_at before update on public.catalog_import_jobs
for each row execute function public.set_updated_at();
create trigger catalog_import_items_set_updated_at before update on public.catalog_import_items
for each row execute function public.set_updated_at();

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  submission_id bigint references public.catalog_submissions(id) on delete cascade,
  kind text not null check (kind in ('submission_approved', 'submission_imported', 'submission_rejected')),
  message text not null check (char_length(message) between 1 and 500),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, submission_id, kind)
);
create index notifications_user_created_idx on public.notifications(user_id, created_at desc);

create or replace function public.queue_approved_submission()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status = 'approved' and old.status is distinct from new.status then
    insert into public.catalog_import_jobs (submission_id, spotify_type, spotify_id, title, release_kind)
    values (new.id, new.spotify_type, new.spotify_id, new.title,
      case when new.spotify_type = 'album' then 'album' else null end)
    on conflict (submission_id) do update set
      status = case when public.catalog_import_jobs.status in ('completed','completed_with_errors')
        then public.catalog_import_jobs.status else 'queued' end,
      error_message = null;
  end if;
  return new;
end;
$$;

create trigger catalog_submissions_queue_after_approval
after update of status on public.catalog_submissions
for each row execute function public.queue_approved_submission();

create or replace function public.notify_submission_result()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status is distinct from old.status and new.status in ('approved', 'imported', 'rejected') then
    insert into public.notifications (user_id, submission_id, kind, message)
    select supporter.user_id, new.id,
      case new.status when 'approved' then 'submission_approved'
        when 'imported' then 'submission_imported' else 'submission_rejected' end,
      case new.status when 'approved' then 'Zaakceptowano zgłoszenie: ' || new.title
        when 'imported' then 'Dodano do katalogu: ' || new.title
        else 'Odrzucono zgłoszenie: ' || new.title end
    from public.catalog_submission_supporters supporter
    where supporter.submission_id = new.id
    on conflict (user_id, submission_id, kind) do nothing;
  end if;
  if new.status is distinct from old.status and new.status = 'imported' then
    update public.catalog_import_jobs set status='completed', albums_completed=albums_total,
      completed_at=coalesce(completed_at,now()), error_message=null where submission_id=new.id;
  end if;
  return new;
end;
$$;

create trigger catalog_submissions_notify_result
after update of status on public.catalog_submissions
for each row execute function public.notify_submission_result();

-- Save the artist and album cards before fetching every tracklist. This makes a
-- large import useful immediately and lets later runs resume album by album.
create or replace function public.import_spotify_catalog_stubs(payload jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  performer jsonb; release jsonb; credit record;
  performer_id bigint; release_id bigint; primary_id bigint;
  raw_date text; date_precision text; full_date date;
  album_count integer := 0; artist_count integer := 0;
begin
  if payload->>'version' is distinct from '1'
    or jsonb_typeof(payload->'artists') is distinct from 'array'
    or jsonb_typeof(payload->'albums') is distinct from 'array'
    or jsonb_array_length(payload->'albums') not between 1 and 100
    or jsonb_array_length(payload->'artists') not between 1 and 1000 then
    raise exception 'Invalid Spotify catalog stub envelope';
  end if;
  perform pg_advisory_xact_lock(724031906);
  if (select count(*) <> count(distinct item->>'spotify_id') from jsonb_array_elements(payload->'artists') item)
    or (select count(*) <> count(distinct item->>'spotify_id') from jsonb_array_elements(payload->'albums') item) then
    raise exception 'Duplicate or missing Spotify ID';
  end if;

  for performer in select value from jsonb_array_elements(payload->'artists') loop
    if coalesce(performer->>'spotify_id','') !~ '^[A-Za-z0-9]{22}$'
      or coalesce(btrim(performer->>'name'),'') = '' or coalesce(btrim(performer->>'slug'),'') = '' then
      raise exception 'Invalid artist';
    end if;
    insert into public.artists as existing (spotify_id,name,slug,image_url)
    values (performer->>'spotify_id',performer->>'name',performer->>'slug',performer->>'image_url')
    on conflict (spotify_id) do update set name=excluded.name,
      image_url=case when performer ? 'image_url' then excluded.image_url else existing.image_url end,
      updated_at=now();
    artist_count := artist_count + 1;
  end loop;

  for release in select value from jsonb_array_elements(payload->'albums') loop
    if coalesce(release->>'spotify_id','') !~ '^[A-Za-z0-9]{22}$'
      or coalesce(btrim(release->>'title'),'') = '' or coalesce(btrim(release->>'slug'),'') = ''
      or coalesce(release->>'album_type','') not in ('album','ep')
      or jsonb_typeof(release->'artists') is distinct from 'array'
      or jsonb_array_length(release->'artists') < 1 then
      raise exception 'Invalid album stub';
    end if;
    raw_date := release->>'release_date_raw'; date_precision := release->>'release_date_precision';
    if date_precision='year' and raw_date ~ '^[0-9]{4}$' then full_date := null;
    elsif date_precision='month' and raw_date ~ '^[0-9]{4}-[0-9]{2}$' then full_date := null;
    elsif date_precision='day' and raw_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then full_date := raw_date::date;
    else raise exception 'Invalid release date precision'; end if;
    select id into primary_id from public.artists where spotify_id=release->'artists'->>0;
    if primary_id is null then raise exception 'Missing primary artist'; end if;
    insert into public.albums as existing (spotify_id,artist_id,title,slug,cover_url,release_date,release_date_raw,release_date_precision,album_type)
    values (release->>'spotify_id',primary_id,release->>'title',release->>'slug',release->>'cover_url',
      full_date,raw_date,date_precision,release->>'album_type')
    on conflict (spotify_id) do update set artist_id=excluded.artist_id,title=excluded.title,
      cover_url=excluded.cover_url,release_date=excluded.release_date,release_date_raw=excluded.release_date_raw,
      release_date_precision=excluded.release_date_precision,album_type=excluded.album_type,updated_at=now()
    returning id into release_id;
    for credit in select value, ordinality from jsonb_array_elements_text(release->'artists') with ordinality loop
      select id into performer_id from public.artists where spotify_id=credit.value;
      if performer_id is null then raise exception 'Album credit missing from payload'; end if;
      insert into public.album_artists (album_id,artist_id,position) values (release_id,performer_id,credit.ordinality)
      on conflict (album_id,artist_id) do update set position=excluded.position;
    end loop;
    album_count := album_count + 1;
  end loop;
  return jsonb_build_object('version',1,'artists',artist_count,'albums',album_count);
end;
$$;
revoke all on function public.import_spotify_catalog_stubs(jsonb) from public, anon, authenticated;
grant execute on function public.import_spotify_catalog_stubs(jsonb) to service_role;

alter table public.catalog_import_jobs enable row level security;
alter table public.catalog_import_items enable row level security;
alter table public.notifications enable row level security;

create policy import_jobs_admin_read on public.catalog_import_jobs for select to authenticated
using (public.is_catalog_admin());
create policy import_jobs_supporter_read on public.catalog_import_jobs for select to authenticated
using (exists (
  select 1 from public.catalog_submission_supporters supporter
  where supporter.submission_id = catalog_import_jobs.submission_id
    and supporter.user_id = (select auth.uid())
));
create policy import_items_admin_read on public.catalog_import_items for select to authenticated
using (public.is_catalog_admin());
create policy notifications_read_own on public.notifications for select to authenticated
using (user_id = (select auth.uid()));
create policy notifications_update_own on public.notifications for update to authenticated
using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

revoke all on public.catalog_import_jobs, public.catalog_import_items, public.notifications from anon, authenticated;
grant select on public.catalog_import_jobs, public.catalog_import_items to authenticated;
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

revoke all on function public.queue_approved_submission() from public, anon, authenticated;
revoke all on function public.notify_submission_result() from public, anon, authenticated;

-- Backfill still-approved submissions so the new queue is immediately complete.
insert into public.catalog_import_jobs (submission_id, spotify_type, spotify_id, title, release_kind)
select id, spotify_type, spotify_id, title, case when spotify_type='album' then 'album' else null end
from public.catalog_submissions where status='approved'
on conflict (submission_id) do nothing;

notify pgrst, 'reload schema';
commit;
