begin;

create table public.user_lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null constraint user_lists_user_id_fkey references public.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  description text check (description is null or char_length(btrim(description)) between 1 and 500),
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index user_lists_user_name_key on public.user_lists (user_id, lower(btrim(name)));
create index user_lists_public_updated_idx on public.user_lists (user_id, updated_at desc) where is_public;

create table public.user_list_items (
  list_id bigint not null constraint user_list_items_list_id_fkey references public.user_lists(id) on delete cascade,
  album_id bigint not null constraint user_list_items_album_id_fkey references public.albums(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (list_id, album_id)
);

create index user_list_items_album_idx on public.user_list_items (album_id);
create index user_list_items_list_added_idx on public.user_list_items (list_id, added_at desc);

create trigger user_lists_set_updated_at
before update on public.user_lists
for each row execute function public.set_updated_at();

create or replace function public.enforce_user_list_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_name = 'user_lists' then
    if (select count(*) from public.user_lists where user_id = new.user_id) >= 50 then
      raise exception 'User list limit reached';
    end if;
  elsif tg_table_name = 'user_list_items' then
    if (select count(*) from public.user_list_items where list_id = new.list_id) >= 500 then
      raise exception 'List item limit reached';
    end if;
  end if;
  return new;
end;
$$;

create trigger user_lists_limit_before_insert
before insert on public.user_lists
for each row execute function public.enforce_user_list_limits();

create trigger user_list_items_limit_before_insert
before insert on public.user_list_items
for each row execute function public.enforce_user_list_limits();

alter table public.user_lists enable row level security;
alter table public.user_list_items enable row level security;

create policy user_lists_visible_read on public.user_lists
for select to anon, authenticated
using (is_public or user_id = (select auth.uid()));

create policy user_lists_insert_own on public.user_lists
for insert to authenticated
with check (user_id = (select auth.uid()) and public.is_active_user());

create policy user_lists_update_own on public.user_lists
for update to authenticated
using (user_id = (select auth.uid()) and public.is_active_user())
with check (user_id = (select auth.uid()) and public.is_active_user());

create policy user_lists_delete_own on public.user_lists
for delete to authenticated
using (user_id = (select auth.uid()) and public.is_active_user());

create policy user_list_items_visible_read on public.user_list_items
for select to anon, authenticated
using (exists (
  select 1 from public.user_lists list
  where list.id = user_list_items.list_id
    and (list.is_public or list.user_id = (select auth.uid()))
));

create policy user_list_items_insert_own on public.user_list_items
for insert to authenticated
with check (public.is_active_user() and exists (
  select 1 from public.user_lists list
  where list.id = user_list_items.list_id and list.user_id = (select auth.uid())
));

create policy user_list_items_delete_own on public.user_list_items
for delete to authenticated
using (public.is_active_user() and exists (
  select 1 from public.user_lists list
  where list.id = user_list_items.list_id and list.user_id = (select auth.uid())
));

revoke all on public.user_lists, public.user_list_items from anon, authenticated;
grant select on public.user_lists, public.user_list_items to anon, authenticated;
grant insert, update, delete on public.user_lists to authenticated;
grant insert, delete on public.user_list_items to authenticated;
grant usage, select on sequence public.user_lists_id_seq to authenticated;

revoke all on function public.enforce_user_list_limits() from public, anon, authenticated;

notify pgrst, 'reload schema';
commit;
