begin;

create table public.album_cover_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  rating numeric(3,1) not null
    check (rating >= 1 and rating <= 10 and rating * 2 = floor(rating * 2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, album_id)
);

create index album_cover_ratings_album_id_idx
  on public.album_cover_ratings (album_id);

create trigger album_cover_ratings_set_updated_at
before update on public.album_cover_ratings
for each row execute function public.set_updated_at();

alter table public.album_cover_ratings enable row level security;

create policy album_cover_ratings_public_read on public.album_cover_ratings
for select to anon, authenticated using (true);
create policy album_cover_ratings_insert_own on public.album_cover_ratings
for insert to authenticated
with check ((select auth.uid()) = user_id and public.is_active_user());
create policy album_cover_ratings_update_own on public.album_cover_ratings
for update to authenticated
using ((select auth.uid()) = user_id and public.is_active_user())
with check ((select auth.uid()) = user_id and public.is_active_user());
create policy album_cover_ratings_delete_own on public.album_cover_ratings
for delete to authenticated
using ((select auth.uid()) = user_id and public.is_active_user());

revoke all on public.album_cover_ratings from anon, authenticated;
grant select on public.album_cover_ratings to anon, authenticated;
grant insert, update, delete on public.album_cover_ratings to authenticated;
grant usage, select on sequence public.album_cover_ratings_id_seq to authenticated;

create view public.album_cover_rating_summary
with (security_invoker = true)
as
select
  album_id,
  round(avg(rating), 1) as average,
  count(*)::bigint as rating_count
from public.album_cover_ratings
group by album_id;

grant select on public.album_cover_rating_summary to anon, authenticated;

commit;
