begin;

alter table public.artists
  add column real_name text,
  add column birth_date date,
  add column birth_date_precision text
    check (birth_date_precision is null or birth_date_precision in ('day', 'month', 'year')),
  add column birth_place text,
  add column enrichment_status text not null default 'pending'
    check (enrichment_status in ('pending', 'running', 'enriched', 'review', 'not_found', 'failed')),
  add column enrichment_source text
    check (enrichment_source is null or enrichment_source in ('wikidata', 'musicbrainz', 'manual')),
  add column enrichment_source_id text,
  add column enrichment_source_url text,
  add column enrichment_confidence double precision
    check (enrichment_confidence is null or enrichment_confidence between 0 and 1),
  add column enrichment_checked_at timestamptz,
  add column enrichment_error text,
  add column enrichment_field_sources jsonb not null default '{}'::jsonb
    check (jsonb_typeof(enrichment_field_sources) = 'object');

create table public.artist_enrichment_candidates (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  source text not null check (source in ('wikidata', 'musicbrainz')),
  source_id text not null,
  source_url text not null,
  candidate_data jsonb not null check (jsonb_typeof(candidate_data) = 'object'),
  match_evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(match_evidence) = 'object'),
  confidence double precision not null check (confidence between 0 and 1),
  status text not null default 'pending' check (status in ('pending', 'applied', 'rejected')),
  reviewed_by uuid references public.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (artist_id, source, source_id)
);

create index artists_enrichment_queue_idx
  on public.artists(enrichment_status, catalog_visible, id);
create index artist_enrichment_candidates_review_idx
  on public.artist_enrichment_candidates(status, created_at desc);

alter table public.artist_enrichment_candidates enable row level security;

create policy artist_enrichment_candidates_admin_read
  on public.artist_enrichment_candidates for select to authenticated
  using (public.is_catalog_admin());

revoke all on table public.artist_enrichment_candidates from public, anon, authenticated;
grant select on table public.artist_enrichment_candidates to authenticated;
grant all on table public.artist_enrichment_candidates to service_role;
grant usage, select on sequence public.artist_enrichment_candidates_id_seq to service_role;

notify pgrst, 'reload schema';
commit;
